name: Bug Report
description: File a bug report to help us improve BranChat
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Web (Browser)
        - macOS Electron App
        - Both
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g., macOS 14.1, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (if Web)
      description: Which browser and version? (if applicable)
      placeholder: e.g., Chrome 120, Safari 17, Firefox 121

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: If running locally, what Node.js version?
      placeholder: e.g., v18.17.0

  - type: dropdown
    id: model
    attributes:
      label: AI Model
      description: Which AI model were you using when the bug occurred?
      options:
        - GPT-4
        - GPT-3.5 Turbo
        - Claude 3.5 Sonnet
        - Claude 3 Opus
        - Claude 3 Haiku
        - Gemini 1.5 Pro
        - Gemini 1.5 Flash
        - Grok Beta
        - Not applicable

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: Any relevant console errors or logs (check browser DevTools Console)
      placeholder: Paste console output here
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other details...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I am using the latest version of BranChat
          required: false
        - label: I have included all relevant information above
          required: true
